apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-nfs-pv
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: rpi4-master
    path: "/data/"
  mountOptions:
  - nfsvers=4.2
